pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    sh 'sudo docker build -t mahendra283/nice-job.'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Log in to a Docker registry (e.g., Docker Hub)
                    sh 'sudo docker login -u mahendra283 -p Bannu283@'

                    // Push the Docker image to the registry
                    sh 'sudo docker push mahendra283/nice-job'
                }
            }
        }
    }
}
